# NumPy 
## 1-D

In [2]:
#library 
import numpy as np

a = np.array([1,2,4,5,6])
a

array([1, 2, 4, 5, 6])

In [3]:
type(a)

numpy.ndarray

In [6]:
    b = np.array([[1,3,4,5,6],[2,3,5,6,7]])
    b

array([[1, 3, 4, 5, 6],
       [2, 3, 5, 6, 7]])

In [7]:
type(b)

numpy.ndarray

In [8]:
c= np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [10]:
d = np.ones(4)
d

array([1., 1., 1., 1.])

In [12]:
e= np.arange(2,10)
e

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
f = np.arange(2,10,2)
f

array([2, 4, 6, 8])

In [16]:
l = np.linspace(2,10,num=5) # gives five Number with equal difference
l

array([ 2.,  4.,  6.,  8., 10.])

In [18]:
h = np.ones(5,dtype=np.int8)
h

array([1, 1, 1, 1, 1], dtype=int8)

In [19]:
h = np.ones(5,dtype=np.float64)
h

array([1., 1., 1., 1., 1.])

## 2-D

In [23]:
import numpy as np
d2 = np.ones((2,4))
d2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
d2 = np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
d2 = np.empty((4,4))
d2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3-D

In [37]:
D3 = np.arange(24).reshape(2,3,4)
D3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Functions and N Dimension

In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)


[[[[[1 2 3 4]]]]]


In [39]:
print('number of dimensions :', arr.ndim)

number of dimensions : 5


In [41]:


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


### Slicing

In [42]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


### Functions

In [43]:
arr = np.array([1,2,3,4,5,66,54,65,9])

arr.sort()
arr

array([ 1,  2,  3,  4,  5,  9, 54, 65, 66])

In [44]:
b = np.array([14,53,64,23,54,65,33,54])

b

array([14, 53, 64, 23, 54, 65, 33, 54])

In [46]:
cont = np.concatenate((arr,b))
cont

array([ 1,  2,  3,  4,  5,  9, 54, 65, 66, 14, 53, 64, 23, 54, 65, 33, 54])

In [48]:
cont.sort()
cont

array([ 1,  2,  3,  4,  5,  9, 14, 23, 33, 53, 54, 54, 54, 64, 65, 65, 66])

## 2-D

In [50]:
D2 = np.array([[1,2,4,5,6],[2,4,5,3,5]])
D2

array([[1, 2, 4, 5, 6],
       [2, 4, 5, 3, 5]])

In [52]:
arr1 = np.array([[2,3],[4,5]])
arr1       

array([[2, 3],
       [4, 5]])

In [53]:
arr2 = np.array([[4,6],[6,8]])
arr2

array([[4, 6],
       [6, 8]])

In [54]:
np.concatenate((arr1,arr2))

array([[2, 3],
       [4, 5],
       [4, 6],
       [6, 8]])

In [55]:
np.concatenate((arr1,arr2),axis=1)

array([[2, 3, 4, 6],
       [4, 5, 6, 8]])

In [56]:
arr1.ndim

2

In [58]:
x = np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
a = x[np.newaxis,:]
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])